### ISSUE TITLE
It good to use, i changed something for myself

### ISSUE THREAD

**Issue by wang-er-s** [BeautyfullCastle/UniSVN#1]
have a error :
in CallSvnStatus func  
'stdError == null always be false , consider use string.IsNullOrEmpty insted'

our project inject this plugin on git project , and through jenkins upload svn，but it will log error, so i write a function check is svn working.  

anyway, it's a good plugin

**Comment by BeautyfullCastle** [comment]
Thank you for your bug report!
I'll change the code ASAP.

**Comment by BeautyfullCastle** [comment]
I changed the code like you said.
c0d4d2fa4fcb19a4720f444ac38fe92e0566e2bc
